/**
 * Elrest eDesign Runtime Library Messages Model Instance
 *
 * @copyright 2024 Elrest AutomationsSysteme GMBH
 */
'use strict';
Object.defineProperty(exports, "__esModule", { value: true });
exports.InstanceMonitor = exports.InstanceOrigin = exports.AlarmOptions = exports.WebSocketServerExecutionOptions = exports.NodeREDExecutionOptions = exports.JSSWorkspaceExecutionOptions = exports.JSScriptExecutionOptions = exports.DataExecutionOptions = exports.ControllerExecutionOptions = exports.AlarmExecutionOptions = exports.WebSocketServerInstance = exports.TrendInstance = exports.JSScriptInstance = exports.JSSWorkspaceInstance = exports.DataInstance = exports.ControllerInstance = exports.AlarmInstance = exports.NodeREDInstance = exports.DataSourceOptions = exports.DataAdapter = exports.Type = exports.WebSocketServerOptions = exports.UDPOptions = exports.TCPOptions = exports.Status = exports.NodeREDOptions = exports.RestartOptions = exports.LogOptions = exports.Instance = exports.ExecutionOptions = exports.ExecutionMode = exports.CronOptions = exports.LogLevel = exports.LogMessageBody = exports.ResourceUsage = exports.WSProtocol = exports.LogDate = exports.Log = exports.APIServerExecutionOptions = exports.APIServerOptions = exports.APIServerInstance = exports.AuthServerInstance = exports.AuthServerExecutionOptions = exports.AuthServerOptions = void 0;
var Log_1 = require("./Log");
Object.defineProperty(exports, "Log", { enumerable: true, get: function () { return Log_1.Log; } });
var LogDate_1 = require("./LogDate");
Object.defineProperty(exports, "LogDate", { enumerable: true, get: function () { return LogDate_1.LogDate; } });
var WSProtocol_1 = require("./WSProtocol");
Object.defineProperty(exports, "WSProtocol", { enumerable: true, get: function () { return WSProtocol_1.WSProtocol; } });
var ResourceUsage_1 = require("./ResourceUsage");
Object.defineProperty(exports, "ResourceUsage", { enumerable: true, get: function () { return ResourceUsage_1.ResourceUsage; } });
var LogLevel_1 = require("./LogLevel");
Object.defineProperty(exports, "LogLevel", { enumerable: true, get: function () { return LogLevel_1.LogLevel; } });
var LogMessageBody_1 = require("./LogMessageBody");
Object.defineProperty(exports, "LogMessageBody", { enumerable: true, get: function () { return LogMessageBody_1.LogMessageBody; } });
var CronOptions_1 = require("./CronOptions");
Object.defineProperty(exports, "CronOptions", { enumerable: true, get: function () { return CronOptions_1.CronOptions; } });
var ExecutionMode_1 = require("./ExecutionMode");
Object.defineProperty(exports, "ExecutionMode", { enumerable: true, get: function () { return ExecutionMode_1.ExecutionMode; } });
var ExecutionOptions_1 = require("./ExecutionOptions");
Object.defineProperty(exports, "ExecutionOptions", { enumerable: true, get: function () { return ExecutionOptions_1.ExecutionOptions; } });
var Instance_1 = require("./Instance");
Object.defineProperty(exports, "Instance", { enumerable: true, get: function () { return Instance_1.Instance; } });
var LogOptions_1 = require("./LogOptions");
Object.defineProperty(exports, "LogOptions", { enumerable: true, get: function () { return LogOptions_1.LogOptions; } });
var RestartOptions_1 = require("./RestartOptions");
Object.defineProperty(exports, "RestartOptions", { enumerable: true, get: function () { return RestartOptions_1.RestartOptions; } });
var Status_1 = require("./Status");
Object.defineProperty(exports, "Status", { enumerable: true, get: function () { return Status_1.Status; } });
var NodeREDOptions_1 = require("./NodeREDOptions");
Object.defineProperty(exports, "NodeREDOptions", { enumerable: true, get: function () { return NodeREDOptions_1.NodeREDOptions; } });
var WebSocketServerOptions_1 = require("./WebSocketServerOptions");
Object.defineProperty(exports, "WebSocketServerOptions", { enumerable: true, get: function () { return WebSocketServerOptions_1.WebSocketServerOptions; } });
var DataAdapter = require("./DataAdapter");
exports.DataAdapter = DataAdapter;
var Type_1 = require("./Type");
Object.defineProperty(exports, "Type", { enumerable: true, get: function () { return Type_1.Type; } });
var TCPOptions_1 = require("./TCPOptions");
Object.defineProperty(exports, "TCPOptions", { enumerable: true, get: function () { return TCPOptions_1.TCPOptions; } });
var UDPOptions_1 = require("./UDPOptions");
Object.defineProperty(exports, "UDPOptions", { enumerable: true, get: function () { return UDPOptions_1.UDPOptions; } });
var DataSourceOptions_1 = require("./DataSourceOptions");
Object.defineProperty(exports, "DataSourceOptions", { enumerable: true, get: function () { return DataSourceOptions_1.DataSourceOptions; } });
var NodeREDInstance_1 = require("./NodeREDInstance");
Object.defineProperty(exports, "NodeREDInstance", { enumerable: true, get: function () { return NodeREDInstance_1.NodeREDInstance; } });
var AlarmOptions_1 = require("./AlarmOptions");
Object.defineProperty(exports, "AlarmOptions", { enumerable: true, get: function () { return AlarmOptions_1.AlarmOptions; } });
var AlarmInstance_1 = require("./AlarmInstance");
Object.defineProperty(exports, "AlarmInstance", { enumerable: true, get: function () { return AlarmInstance_1.AlarmInstance; } });
var ControllerInstance_1 = require("./ControllerInstance");
Object.defineProperty(exports, "ControllerInstance", { enumerable: true, get: function () { return ControllerInstance_1.ControllerInstance; } });
var DataInstance_1 = require("./DataInstance");
Object.defineProperty(exports, "DataInstance", { enumerable: true, get: function () { return DataInstance_1.DataInstance; } });
var JSSWorkspaceInstance_1 = require("./JSSWorkspaceInstance");
Object.defineProperty(exports, "JSSWorkspaceInstance", { enumerable: true, get: function () { return JSSWorkspaceInstance_1.JSSWorkspaceInstance; } });
var JSScriptInstance_1 = require("./JSScriptInstance");
Object.defineProperty(exports, "JSScriptInstance", { enumerable: true, get: function () { return JSScriptInstance_1.JSScriptInstance; } });
var TrendInstance_1 = require("./TrendInstance");
Object.defineProperty(exports, "TrendInstance", { enumerable: true, get: function () { return TrendInstance_1.TrendInstance; } });
var WebSocketServerInstance_1 = require("./WebSocketServerInstance");
Object.defineProperty(exports, "WebSocketServerInstance", { enumerable: true, get: function () { return WebSocketServerInstance_1.WebSocketServerInstance; } });
var AlarmExecutionOptions_1 = require("./AlarmExecutionOptions");
Object.defineProperty(exports, "AlarmExecutionOptions", { enumerable: true, get: function () { return AlarmExecutionOptions_1.AlarmExecutionOptions; } });
var ControllerExecutionOptions_1 = require("./ControllerExecutionOptions");
Object.defineProperty(exports, "ControllerExecutionOptions", { enumerable: true, get: function () { return ControllerExecutionOptions_1.ControllerExecutionOptions; } });
var DataExecutionOptions_1 = require("./DataExecutionOptions");
Object.defineProperty(exports, "DataExecutionOptions", { enumerable: true, get: function () { return DataExecutionOptions_1.DataExecutionOptions; } });
var JSScriptExecutionOptions_1 = require("./JSScriptExecutionOptions");
Object.defineProperty(exports, "JSScriptExecutionOptions", { enumerable: true, get: function () { return JSScriptExecutionOptions_1.JSScriptExecutionOptions; } });
var JSSWorkspaceExecutionOptions_1 = require("./JSSWorkspaceExecutionOptions");
Object.defineProperty(exports, "JSSWorkspaceExecutionOptions", { enumerable: true, get: function () { return JSSWorkspaceExecutionOptions_1.JSSWorkspaceExecutionOptions; } });
var NodeREDExecutionOptions_1 = require("./NodeREDExecutionOptions");
Object.defineProperty(exports, "NodeREDExecutionOptions", { enumerable: true, get: function () { return NodeREDExecutionOptions_1.NodeREDExecutionOptions; } });
var WebSocketServerExecutionOptions_1 = require("./WebSocketServerExecutionOptions");
Object.defineProperty(exports, "WebSocketServerExecutionOptions", { enumerable: true, get: function () { return WebSocketServerExecutionOptions_1.WebSocketServerExecutionOptions; } });
var InstanceOrigin_1 = require("./InstanceOrigin");
Object.defineProperty(exports, "InstanceOrigin", { enumerable: true, get: function () { return InstanceOrigin_1.InstanceOrigin; } });
var APIServerInstance_1 = require("./APIServerInstance");
Object.defineProperty(exports, "APIServerInstance", { enumerable: true, get: function () { return APIServerInstance_1.APIServerInstance; } });
var APIServerOptions_1 = require("./APIServerOptions");
Object.defineProperty(exports, "APIServerOptions", { enumerable: true, get: function () { return APIServerOptions_1.APIServerOptions; } });
var APIServerExecutionOptions_1 = require("./APIServerExecutionOptions");
Object.defineProperty(exports, "APIServerExecutionOptions", { enumerable: true, get: function () { return APIServerExecutionOptions_1.APIServerExecutionOptions; } });
var InstanceMonitor_1 = require("./InstanceMonitor");
Object.defineProperty(exports, "InstanceMonitor", { enumerable: true, get: function () { return InstanceMonitor_1.InstanceMonitor; } });
var AuthServerOptions_1 = require("./AuthServerOptions");
Object.defineProperty(exports, "AuthServerOptions", { enumerable: true, get: function () { return AuthServerOptions_1.AuthServerOptions; } });
var AuthServerExecutionOptions_1 = require("./AuthServerExecutionOptions");
Object.defineProperty(exports, "AuthServerExecutionOptions", { enumerable: true, get: function () { return AuthServerExecutionOptions_1.AuthServerExecutionOptions; } });
var AuthServerInstance_1 = require("./AuthServerInstance");
Object.defineProperty(exports, "AuthServerInstance", { enumerable: true, get: function () { return AuthServerInstance_1.AuthServerInstance; } });
